apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labbox
  namespace: labbox
  labels:
    app: labbox-ephys
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi
