apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-labbox-ephys-ephys1-b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: linode-block-storage-retain
