apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: labbox-ephys-dev3
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
