apiVersion: apps/v1
kind: Deployment
metadata:
  name: labbox-ephys-deployment
  labels:
    app: labbox-ephys
spec:
  replicas: 1
  selector:
    matchLabels:
        app: labbox-ephys
  template:
    metadata:
      labels:
        app: labbox-ephys
    spec:
      volumes:
        - name: labbox-ephys-pv-storage
          persistentVolumeClaim:
            claimName: labbox-ephys-pv-claim
      containers:
      - name: labbox-ephys
        image: magland/labbox-ephys:0.3.14
        imagePullPolicy: Always
        env:
        - name: HOME
          value: /tmp
        - name: KACHERY_P2P_START_DAEMON_OPTS
          value: --port 14107 --host ephys1.laboratorybox.org
        - name: LABBOX_EPHYS_DEPLOY
          value: ephys1
        ports:
        - containerPort: 15310
        volumeMounts:
          - mountPath: "/data"
            name: labbox-ephys-pv-storage
