apiVersion: v1
kind: Service
metadata:
    name: labbox-ephys-service
spec:
    selector:
        app: labbox-ephys
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 15310
    - name: websocket
      protocol: TCP
      port: 15308
      targetPort: 15308
    type: LoadBalancer
