name: Node.js CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - magland/issue222
defaults:
  run:
    shell: bash
jobs:
  install_jupyterlab:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.8'
      - run: python --version
      - run: conda info
      - run: conda list
      - run: conda install jupyterlab
      - run: conda install -c conda-forge nodejs
      - run: conda list
      - run: pip install wheel
      - run: pip install -e ./python
      - run: pip --version && python --version && pip install -e jupyterlab/labbox_ephys_widgets_jp
      - run: conda list
      - run: jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
      - run: jupyter labextension install jupyterlab/labbox_ephys_widgets_jp
      - run: jupyter labextension list