name: Node.js CI
on:
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
    working-directory: scripts
jobs:
  install_jupyterlab:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: labbox
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - run: conda install jupyterlab
      - run: conda install -c conda-forge nodejs
      - run: pip install -e ./python
      - run: pip install -e jupyterlab/labbox_ephys_widgets_jp
      - run: jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
      - run: jupyter labextension install jupyterlab/labbox_ephys_widgets_jp
      - run: jupyter labextension list